### ISSUE TITLE
IE11 Tests are Executed Twice

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1060]
The whole batch of IE11 tests are executed twice per job

For example, see console output here: https://circleci.com/gh/Automattic/wp-e2e-tests-ie11/322

**Comment by alisterscott** [comment]
Change in #1059 didn't fix this issue, see: https://circleci.com/gh/Automattic/wp-e2e-tests-ie11/323

@hoverduck I know you worked on this just before your move, would you have any ideas why the test block would execute twice? It looks like it's being called twice but it doesn't look like it:

https://github.com/Automattic/wp-e2e-tests-ie11/blob/master/circle.yml#L26

**Comment by hoverduck** [comment]
Looks like it's because the circle.yml file runs the tests with `./run.sh -R -w $RUN_ARGS`, and `$RUN_ARGS` duplicates the `-w` argument (also `-R`, but that one doesn't seem to impact anything).

I updated the cron job to remove those arguments.  The next scheduled run is in a few hours, we can close this issue after that verifies that it's working.

**Comment by alisterscott** [comment]
Thanks @hoverduck
