### ISSUE TITLE
Investigate why specs aren't being randomly ordered

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1206]
When executing this project in CircleCI the spec execution order used to be randomized, however it doesn't look like this is happening any more

**Comment by brbrr** [comment]
I've looked at recent CI builds, and it looks like the spec files are always runs in random order. Could you explain your concerns a bit more?

**Comment by alisterscott** [comment]
@brbrr I thought something like this wasn't random?

https://circleci.com/gh/Automattic/wp-e2e-tests/19982

Maybe it's just branches not scheduled cron job runs?

**Comment by brbrr** [comment]
Ah, you were talking about test(`describe`) randomness. Right now we randomizing file ordering, not the tests itself.
Check these 2 jobs:
https://circleci.com/gh/Automattic/wp-e2e-tests/19982
https://circleci.com/gh/Automattic/wp-e2e-tests/19991

I think it was like that since I joined. Randomizing `describe` blocks are doable, but I personally don't see much benefit in this. Since we resetting browser state before every test. 

Also, I think we would need to
- get rid of `describe` nesting and tweak/write from scratch randomizer plugin for mocha due to our test structure(which is breaking mocha conventions)
OR
- reorganize our tests, so all the tests would be organized in `it` blocks.

**Comment by alisterscott** [comment]
Oh, ok, I understand now. I don't think we need to random order the describe blocks. I'll close this for now.
