### ISSUE TITLE
Theme test sometimes fails

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1393]
The theme test sometimes fails, 

https://21850-57936731-gh.circle-artifacts.com/0/home/circleci/wp-e2e-tests/screenshots/FAILED-EN-MOBILE-can-see-theme-details-page-and-open-the-live-demo-1533529831243.png

https://circleci.com/gh/Automattic/wp-e2e-tests/21850#artifacts/containers/0

```
  1) [WPCOM] Switching Themes: (mobile) Switching Themes @parallel @jetpack @visdiff Can switch free themes Can see theme details page and open the live demo:
04:30:31      TimeoutError: Timed out waiting for element with css selector of 'a.theme__sheet-preview-link,li.is-theme-preview a' to be clickable
04:30:31 Wait timed out after 20025ms
04:30:31       at /home/circleci/wp-e2e-tests/node_modules/selenium-webdriver/lib/promise.js:2201:17
04:30:31       at process._tickCallback (internal/process/next_tick.js:68:7)
```

I believe this is due to https://github.com/Automattic/wp-calypso/issues/25720

**Comment by rachelmcr** [comment]
In Automattic/wp-calypso#25720 it looks like the button not being present is because the theme is active on the site already. Note that in your second screenshot in that issue there's a "Customize site" button (which shows when you view the details for your site's active theme) at the top of the page instead of an "Activate this design" button.

Could this be happening because our theme switch tests are running in parallel? (That is, while one test is opening the theme details another test is activating that theme on the site.)

I'll watch for this failure to pop up again — now that we're capturing videos for failed tests, we could verify if that's happening when this test fails.
