### ISSUE TITLE
Issue with Chrome resizing for Woo Commerce Mobile Tests

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1500]
Since https://github.com/Automattic/wp-e2e-tests/pull/1495 was merged the woocommerce on wp.com mobile tests have been failing

There's something weird about logging on when the browser is resized down to mobile size when running the woocommerce tests

As soon as I created a branch with reverting the changes the woocommerce tests pass here: https://circleci.com/gh/Automattic/wp-e2e-tests-woocommerce/1136

@bsessions85 do you have any ideas about this? 

This is a passing test when reverting the resize: https://circleci.com/gh/Automattic/wp-e2e-tests-woocommerce/1136
This is failing against master: https://circleci.com/gh/Automattic/wp-e2e-tests-woocommerce/1132

**Comment by bsessions85** [comment]
This is an interesting one. For some reason, when using the mobileEmulation mode, there can be conflicts when the tests are running in parallel. I found two ways around this. The first way is to run the tests in chrome headless mode. The second way is to run each test on a different display. Since the video recording already runs the tests in separate displays, I opted to turn on the recording for the the woocommerce wrapper repo and the issue is resolved.

It is also worth noting that I saw similar behavior when running in parallel on my macbook. Running tests one at a time causes them to pass.
