### ISSUE TITLE
Selecting wrong menu items

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#1530]
If you run the tests without retrying it's common to see the tests selecting the wrong item in the menu sidebar and then failing as the incorrect screen is shown

Something is funky with how we click these sidebar items - we should investigate why

To reproduce change   `"max_test_attempts": 3,` to   `"max_test_attempts": 1,` in `magellan.json` and commit the change to see the failures in CircleCI for a branch

**Comment by Stojdza** [comment]
This happened recently for 'People' page when I ran tests locally. It was failing randomly. 
@alisterscott What do you think to change the way how we are getting these elements? Instead of `'.sites-navigation [data-tip-target="people"] a'` to add data-e2e attribute to class `menu-link-text` for every item in sidebar?

<img width="867" alt="screen shot 2018-10-18 at 14 39 02" src="https://user-images.githubusercontent.com/7116222/47171823-1299c080-d30a-11e8-8b59-10b8828b978c.png">

**Comment by alisterscott** [comment]
> We can pass .menu-link-text as a selector and item name from the sidebar to selectElementByText()

I think we should try to avoid selecting menu items by text since they're translated and won't work in other languages, eg for i18n tests, and also menu text is more likely to change than a specific attribute. Or do I misunderstand something?

**Comment by alisterscott** [comment]
> We can pass .menu-link-text as a selector and item name from the sidebar to selectElementByText()

I think we should try to avoid selecting menu items by text since they're translated and won't work in other languages, eg for i18n tests, and also menu text is more likely to change than a specific attribute. Or do I misunderstand something?

**Comment by Stojdza** [comment]
@alisterscott I replied to this comment [here](https://github.com/Automattic/wp-e2e-tests/pull/1540#issuecomment-431930428). So yes, data e2e attribute would be more stable solution.
