### ISSUE TITLE
Put all CI scripts into one place

### ISSUE THREAD

**Issue by chenchaoyi** [Automattic/wp-e2e-tests#454]
Currently there are plenty of scripts (randomize.sh, trigger-circle-ci-* etc) in the top repo level for running CI. Any objection on putting them in one `scripts` directory so developers might get less confused on setting things up locally ?

**Comment by hoverduck** [comment]
:+1:

**Comment by alisterscott** [comment]
Sounds good to me. 

Should we look at using something like make, or using npm scripts to do this rather than our own shell script?

**Comment by hoverduck** [comment]
The reason I wrote `run.sh` to begin with was because we had too many different tests and npm scripts was getting crowded and unreadable.  But I'd be open to exploring other options.

I like shell scripting because that's just how I've always done things, and I like the level of control...but I know there are plenty of other test runners that could result in a cleaner view of things.
