### ISSUE TITLE
Investigate why failed tests show as passed in CircleCI

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#511]
Since we introduced the new test runner it looks like every build is passing even if tests are failing within the build.

eg. https://circleci.com/gh/Automattic/wp-e2e-tests/8888

Shows as passed overall, but failed tests

**Comment by alisterscott** [comment]
This might be something to do with automatic retries.

This build failed: https://circleci.com/gh/Automattic/wp-e2e-tests/8901

**Comment by hoverduck** [comment]
Yeah, this is just automatic retries in action.  If you look at the build output in 8888, specifically search out the text "as a Follower" to see the first failing invite test:

```
--> Worker 3, mock port:12021, running test: Invites: (mobile) Inviting New User as a Follower: @parallel @chrome
(7 / 31) <-- Worker 3 FAIL (will retry).  Spent 25481 msec Invites: (mobile) Inviting New User as a Follower: @parallel @chrome
--> Worker 2, mock port:12093, running test: Invites: (mobile) Inviting New User as a Follower: @parallel @chrome
(31 / 31) <-- Worker 2 PASS  Invites: (mobile) Inviting New User as a Follower: @parallel @chrome
```

You can see there that Worker 3 started the test, then failed.  Then later Worker 2 picked it up and it passed.

Looking at build 8901 in your second comment you can see that the Post-NUX test failed, was retried, and the failed again (which is why the build itself was marked as failed):

```
--> Worker 3, mock port:12045, running test: Post-NUX Flows (desktop) @parallel @chrome
(16 / 31) <-- Worker 3 FAIL (will retry).  Spent 63975 msec Post-NUX Flows (desktop) @parallel @chrome
--> Worker 2, mock port:12096, running test: Post-NUX Flows (desktop) @parallel @chrome
(31 / 31) <-- Worker 2 FAIL  Post-NUX Flows (desktop) @parallel @chrome
```
