### ISSUE TITLE
Work out why woocommerce branches no longer run WooCommerce e2e tests

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#514]

**Comment by alisterscott** [comment]
Same for Jetpack tests on jetpack/jp branches

**Comment by hoverduck** [comment]
Sorry, @alisterscott, that was my fault.  That handling is all done in the run-wrapper script, which I cut out of the loop with the move to CircleCI 2.0.  I've added it back in with #521

**Comment by hoverduck** [comment]
Scratch that, for some reason that PR worked fine in its own branch, and the first run on master...but then every run after that was timing out on launching the browser.  I can't explain it, but reverting solved the problem.

I started troubleshooting it, but haven't gotten anywhere yet.  It'll take some time to go through a few different test runs with debug output to figure out where the issue is, and I don't have time to get through it this afternoon.  So I'm re-opening this issue to make sure it doesn't get lost, and I'll try to hammer it out in the morning.

**Comment by hoverduck** [comment]
Fixed in a combination of #526 and #527
