### ISSUE TITLE
Test Jetpack plugin purchase flows

### ISSUE THREAD

**Issue by beaulebens** [Automattic/wp-e2e-tests#560]
We have a number of flows that originate within the plugin, send a user to jetpack.com (for more information) and then send them directly into the shopping cart within WordPress.com. I'd love to be able to test these as "end to end" as possible, but at least from jetpack.com through to wordpress.com.

To see one, install/activate/connect Jetpack on a new WordPress. Go to the Updates screen within wp-admin and see a prompt for enabling backups. It should have a URL something like:

`https://jetpack.com/redirect/?source=jitm-backup-updates&site={site}`

When you land on that page, there's a "Start Backup Up" button with a URL that looks like:

`https://wordpress.com/checkout/{site}/jetpack-personal`

and when you click that, you should land directly in the wordpress.com shopping cart, with a Jetpack Personal plan selected/added to your cart.

cc @richardmuscat who can probably provide some better detail/more examples of the flows we'd like to test here.

**Comment by lancewillett** [comment]
A bit of internal dialogue for reference when we work on this: p1496705502404875-slack-e2e-testing-discuss

**Comment by hoverduck** [comment]
Thanks for the info, @beaulebens.  

It sounds like a relatively straightforward scenario, but how deep the testing goes raises some implementation questions.  Do we need to go all the way through the purchase flow and verify the plan and features are active on the site?  Obviously that's ideal, but right now we're not set up to handle anything like that.  All of our current tests are just UI-focused, and require an existing Jetpack site (we have a few created on the more popular hosts).  And since the sites are distinct and pre-created we can't execute changes against them like plan activation, since subsequent tests runs would then have a different starting point.

So for the immediate future I can add a test to go through the purchase flow as far as adding the plan to the shopping cart and verifying that I get to the payment screen before quitting, but that's it.  That's how we're currently handling domain registration tests on wpcom.

But for the longer term we would like to get a more dynamic setup built that can create new Jetpack sites on the fly.  Not only would that let us test this scenario better, but enables a wider array of tests against things like different versions of Jetpack/WP/PHP/etc.

So if catching this breakage is a high enough priority, we could use this as the driver to go do that work now.  Otherwise we can just do the easy piece now and count on better tests sometime in the future.

**Comment by beaulebens** [comment]
Oh really good questions. I had actually assumed that we'd just do them through to the point of confirming that they were in the cart/about to make payment. Maybe as a separate thing we can figure out how to test the install/configure process that happens after the purchase itself, but I agree that that's a different thing.

I think just testing things through to getting a plan in the cart is good as a first step, but definitely interested in those more advanced tests down the line. I know @rcoll, @gravityrail and @ebinnion have all worked on testing environments at least tangentially related to this, so maybe something they've done can help with the next generation of things.

**Comment by ebinnion** [comment]
I've been using a service called ServerPilot. It's a free management system for a DigitalOcean droplet. It comes with an API and allow creating WP sites with varying PHP versions and other details on the fly. 

@gravityrail and I took advantage of this to build a tool that allows us to provision JPS sites on demand. You should be able to check it out by logging in to  http://jpphp.ericbinnion.com/wp-admin and then creating a new "Jetpack Site".

Note: The above is not a perfect tool by any means.

I've found the ServerPilot API to be super easy to work with for what it's worth.
