### ISSUE TITLE
Specify node version in one place

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#620]
We currently specify our node version in both `.nvmrc` and `circle.yml`

It would be great to only have this specified in one place (prefer `.nvmrc`) and have circle use this value which it currently doesn't do

**Comment by hoverduck** [comment]
I didn't even realize we had the `.nvmrc` file at all!  For my personal use I have the node version defined per project/directory via https://direnv.net/ config.  TIL.

I'll assign this to myself to take a look at.  It'll have be a change to the Dockerfile to start using nvm instead of downloading the specified Node version directly.

**Comment by hoverduck** [comment]
Another thought on this - it would be nice if the Node version was respected in the wrapper repos as well, so we don't have to update all of them.  At the moment they all have different versions specified.
