### ISSUE TITLE
Can't find localization_data.json

### ISSUE THREAD

**Issue by wowazzz** [Automattic/wp-e2e-tests#664]
Can't run search-wordpress-on-google.js test, because

> Error: Cannot find module '../../localization_data.json'

Where I can get an example for this file?
Thanks.

**Comment by rachelmcr** [comment]
@wowazzz You can find the `localization_data.json` file in our i18n wrapper repo here:

https://github.com/Automattic/wp-e2e-tests-i18n/blob/master/localization_data.json

@hoverduck I guess the spec is set up this way because of how we use that wrapper repo, but would it make sense to move the file into this repo so the spec can be run manually? I can spin up a quick PR for that unless there's another reason to leave it as is.

**Comment by hoverduck** [comment]
I agree, it would be better placed in the core repo.  I thought about making that move when I worked on #635, but the i18n tests were seeing such limited usage I didn't worry about it.

@akirk - do you have any concerns with relocating that file?  You were the last one to update it.

**Comment by wowazzz** [comment]
Thank you

**Comment by akirk** [comment]
@hoverduck no concerns from my side, I think we only did the wrapper repo to exclude some Jetpack tests at the time.
