### ISSUE TITLE
Add 'delete header images' action to empty_blog

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#705]
We run a cron biweekly to empty the test blogs of all posts, etc, but we still have issues every few months or so with the Customizer tests timing out due to too many header images.  This issue is to drive adding it as an additional step to our cleanup action.

Sample code - 18d4f-pb

**Comment by bsessions85** [comment]
@hoverduck Where can I find this sample code? I've looked around but haven't been able to find it.

**Comment by lancewillett** [comment]
I looked at this today. A few thoughts:

1) I don't think we need an extra function or step to clear only header images, because the `empty_blog` already removes all attachments. (See D10859-code for the starting point of the removal of header images just for NUX test sites.)
2) We can simply add a cron for the NUX test site, and all its content will be cleared.

**Comment by lancewillett** [comment]
Closing as we should be able to solve without any code changes to the `empty_blog` script.

**Comment by alisterscott** [comment]
> We can simply add a cron for the NUX test site, and all its content will be cleared.

Thanks @lancewillett, I can take care of this
