### ISSUE TITLE
Test login via magic link

### ISSUE THREAD

**Issue by hoverduck** [Automattic/wp-e2e-tests#730]
With https://github.com/Automattic/wp-calypso/pull/18239 the ability to login via magic link is now live in production.

To support it via our e2e tests we'll need to make sure that

A) The `defaultUser` account in NODE_CONFIG was created with a Mailosaur e-mail address
B) That e-mail address needs to be added to the config (but watch out for just adding a third entry to the user in `testAccounts`, because that may break our Jetpack check [[here]]( https://github.com/Automattic/wp-e2e-tests/blob/master/lib/flows/login-flow.js#L33))

**Comment by alisterscott** [comment]
Would this be a separate standalone test? Not changing all existing logins to use magic links?

**Comment by hoverduck** [comment]
Right...and would have to be gated to only run against the main test suite, not Jetpack (or Canary).

**Comment by alisterscott** [comment]
I started working on this today but it's going to be tricky as we don't have a unique email for each magic link requested, and since we're using the one defaultUser account if there's multiple instances of a test running it will be hard to know which link is which, and which link has been used and which hasn't. It's also hard to determine whether the email coming in is new or from a previous run.

The only possible solution I can think of is working with the magic links devs to see whether we could add some meta data to an email to know that it's from a particular run, but seems messy.

@hoverduck: any ideas how to do this neatly so it runs consistently? For the invites and new sign ups we generate emails with a guid and poll for that particular email address we're looking for.

**Comment by alisterscott** [comment]
I decided to add this on the end of the free sign up test since we have a unique email each time, and since it's a unique sign up we won't have any clashes for magic links. Using a shared account to request magic links will be very messy
