### ISSUE TITLE
Should wrapper repo's use CircleCI 2.0?

### ISSUE THREAD

**Issue by alisterscott** [Automattic/wp-e2e-tests#783]
I noticed our wrapper repo's:

https://circleci.com/gh/Automattic/wp-e2e-tests-canary
https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches
https://circleci.com/gh/Automattic/wp-e2e-tests-jetpack
https://circleci.com/gh/Automattic/wp-e2e-tests-woocommerce

all use CircleCI 1.0 (not Docker)

Should we use 2.0 with Docker?

Any difficulties in doing this?

**Comment by hoverduck** [comment]
I don't think we should pursue updating the wrapper repos to 2.0 right now.  It would be nice to have for the usual reasons of consistency, but it introduces some unnecessary overhead.

The problem is that the best practice is to define a specific version of the Docker image for use in each repo in order to guarantee that you're operating against a working config.  So that means that if we update the `wp-e2e-tests` repo to a new image version then we have to also go touch every wrapper repo to make it pull the new version.  We could of course skip that by just using the default `latest` version, but then we get into trouble if we want to start experimenting with anything new and a repo pulls the wrong one.

So before we do that we should figure out a different build scheme that gives us the control we need.  Maybe something with #781?

We could also revisit the idea of the wrapper repos altogether.  As far as I know they're still the best way to logically separate the configs and outputs of the different test groupings, but maybe there's something else we haven't thought of?

**Comment by alisterscott** [comment]
> We could also revisit the idea of the wrapper repos altogether. As far as I know they're still the best way to logically separate the configs and outputs of the different test groupings, but maybe there's something else we haven't thought of?

Sounds like a good idea to think about this

**Comment by hoverduck** [comment]
Thinking out loud -

The reason we introduced the wrapper repos to begin with was because we were having issues with the outputs from different test groups being mixed, making it hard to distinguish a visdiff failure from an actual test failure.  This shows up in two places - the Slack channel and the CircleCI build listings.

I don't think there's any way to get around the CircleCI UI other than having separate repos....they just don't provide any options for additional tagging/filtering.  We could maybe introduce a client-side Tampermonkey script to do something, but I'm not sure if it's worth the effort.  We could just as easily look into different CI providers.

The other piece - Slack notifications - we could address by taking advantage of more of the [config options](https://github.com/lorenwest/node-config/wiki/Configuration-Files) to provide a tiered configuration setup.  We'd just need to echo out the config files from envvars before running the tests, based off of triggers in the `build_parameters`.

Internal reference - p6fDka-i9-p2

**Comment by alisterscott** [comment]
We're now fully on CircleCI 2.0 for all wrappers 🎉
